# Conclusion

## TakeWays

1. The distributions of rating from both IMDB and Douban dataset are similar. Expecially, when we eliminated the effect of scoring mechanism, the difference between them is very small.

2. There does exist some movies which have big difference on the rating for different websites, the main reason would be the culture difference. 

3. The change of genre over year is slightly, since the Drama covers so much ground, it would always take the largest part in  the movie market. And due to the effect of epidemic, there existed a rapid decreases in the movie market.

4. With the development of Internet, more and more people are willing to share their ideas. At the same time, with the improvement of people's appreciation ability and pubalic increase their standard of judgement a good film, the number of films with high scores has decreased significantly.


## Limitations

1. When we retrieve data from website, sometimes the website would have mechanism like anti-website-crawling. It would give some limitations on getting data before analysis.

2. The website also change their arrangment frequently, some websites even change timely, the code based on these websites could be disabled after the arrangment changed. So if we want reproduce our result, it would be helpful to find some websites or links that have consistent arrangment.

3. The data format retrieved from website sometimes would be messy, so it would cause some limitations on data analysis.

4. For our project, the limitation is the different size of dataset and different columns in the dataset. What we did was, in some explorations, we found the common data and columns in both dataset. However, it would definitely reduce the size of dateset, which may effect the accuracy.Thus, for the future work, we could expand the size of both dataset to contain more common data.

## Future Works

In our project, we did the second retrieving process, i.e. the first retrieving process is that retrieving data from website, and the second retrieving process is that jump to the link, which we get from the html, and get the other information that could not be obtained in the first step. If want to get more details, such as budget or revenues, we need to do more deep research. Also, as we mentioned in the 'Limitations' part,  for the future work, we could expand the size of both dataset to contain more common data.

Due to time and capacity constraints, we did not capture deeper information on the IMDB webpage related to the development of the movie and its box office. In the future, we have time to go deeper and continue to get some more complex information in real time dynamically, such as the budget of each movie, the cast list, the director, the country of publication, and other data, as well as the process of collecting the number of their followers on social platforms through the list of people who can be obtained from two different web pages.

With this information, we can analyze more movie-related questions: which types of movies make money? What are the controllable factors associated with box office (revenue)? Does the number of followers of actors and directors have a significant impact on box office as well as ratings? How do original movies compare with film adaptations? What are the prominent keywords of movies? What is the share of film origins? etc.

These analysis results in the future works can more comprehensively help us discover the demand of movie-watching users to predict the box office of movies, evaluate the precise marketing of movie producers and theaters, and predict the quality movies recommended by websites and apps for audiences.

In this project, we did some translation automatically during web scraping, since we had a Chinese website. However, there is no guarantee of accuracy. How to choose an intelligent translation tool to deal with foreign languages remains to be considered.

## Lessons Learned

1. Before retrieving data, make sure the website whether change timely or frequently. If want to the result would be reproducible, try to use some websites or link with static format.

2. The consistent of data type would help a lot during the data analysis.

3. Regular expression on web scraping would be very useful.

4. Web scraping would be very time-consuming, how to reduce the runtime is the question during the whole scraping process.

5. Even though the package 'googltrans' would do the translation automatically, there is no guarantee of accuracy. Therefore, using the original dataset would get the most accurate result, compare with the translated result. In this project, we were trying to avoid using the translated title to do some analysis.
