--- 
title: "Exploration of Movie from Two Websites(IMDb and Douban)"
author: "Long Lin & Shiang XuanYuan"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

In recent years, with the development of modernization, people's income level has increased significantly, spiritual and cultural life along with the improvement of material living standard has increasingly become the goal of the majority of urban and rural consumers to pursue, in the past only a small number of people can see the film and television works have now become a mass consumer goods, all over the major and minor cities, become the spiritual life of people's trust and talking at one's leisure. Film works have become a symbol of a trend that increasingly enriches our daily life.At the same time, nowadays, during the epidemic, people need to work from home more often, greatly increasing the time for self-arrangement, and more people choose to watch movies in their leisure time.

We chose this topic for project was because that we both used to go to the movies and all experienced doubts: Why are there more venues for some movies? Why film genres changed over time? What controllable factors are associated with box office? Does the rating of a movie correlate with the number of people watching or reviewing it? The more people review and rate these movies, the more popular they are, the higher the rating they receive? Do movie ratings differ significantly on different movie sites? In fact, this is some of the questions we want to solve through data analysis that come from life. The audience will score and leave comments on the platform after watching a movie, and the pre-sale, scheduling and attendance of each movie are all data. Through data analysis, we can predict the box office of movies, evaluate the precise marketing of film makers and theaters, and predict the quality movies recommended by websites and APPs for the audience.

The core of our project is to uncover the needs of users who watch movies, so one of the central questions is: What are the needs of users that can be uncovered from the data? The data used in this case study are the box office data of 1664 movies from Douban and top 700 movies from IMDB and the factors that influence them, including the year of the movie, the length of the movie, the genre of the movie, the score of the movie on two different websites and the number of ratings, etc. Movie box office can be affected by various factors, such as the length of the movie, the amounts of people views, the type of movie, the era in which the movie was produced, the budget of the movie, and so on. In this project, we will focus on the analysis of the the relation between rating and reviews, the tendency of genre and whether there has a significant difference of rating on different websites.